name: build_deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            asset_name: rv2b-x86_64-linux.gz
            command: gzip
          - os: macos-latest
            target: x86_64-apple-darwin
            asset_name: rv2b-x86_64-macos.gz
            command: gzip
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            asset_name: rv2b-x86_64-windows.zip
            command: zip

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential pkg-config libssl-dev

      - name: Install musl-tools (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Create g++ symlink
        if: runner.os == 'Linux'
        run: sudo ln -s /usr/bin/g++ /usr/bin/x86_64-linux-musl-g++
        
      - name: Install musl-cross (macOS)
        if: runner.os == 'macOS'
        run: brew install filosottile/musl-cross/musl-cross
      
      - name: Build static binary for ${{ matrix.target }}
        uses: houseabsolute/actions-rust-cross@v1
        with:
          target: ${{ matrix.target }}
          command: "build"
          args: "--release"

      - name: Compress binary (Linux/macOS)
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          BINARY_DIR="target/${{ matrix.target }}/release"
          mkdir -p staging
          cp $BINARY_DIR/rv2b staging/
          cd staging
          gzip rv2b
