name: build_deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            asset_name: rv2b-x86_64-linux.gz
            command: gzip
          - os: macos-latest  
            target: x86_64-apple-darwin
            asset_name: rv2b-x86_64-macos.gz
            command: gzip
          - os: windows-latest 
            target: x86_64-pc-windows-msvc
            asset_name: rv2b-x86_64-windows.zip
            command: zip

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
      - uses: [actions/checkout](https://github.com)@v4
    
      - name: Build static binary for ${{ matrix.target }}
        uses: [houseabsolute/actions-rust-cross](https://github.com/houseabsolute/actions-rust-cross)@v1
        with:
          target: ${{ matrix.target }}
          command: "build"
          args: "--release"

      - name: Compress binary (Linux/macOS)
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          BINARY_DIR="target/${{ matrix.target }}/release"
          mkdir -p staging
          cp $BINARY_DIR/rv2b staging/
          cd staging
          gzip rv2b
          cd ..

      - name: Compress binary (Windows)
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          $BINARY_DIR = "target/${{ matrix.target }}/release"
          mkdir staging
          Copy-Item -Path "$BINARY_DIR/rv2b.exe" -Destination staging/
          Compress-Archive -Path staging/* -DestinationPath ${{ matrix.asset_name }}


    - name: Upload artifact
      uses: [actions/upload-artifact](https://github.com)@v4
      with:
        name: rv2b-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/rv2b*
